services:
  postgres:
    container_name: postgres-sql-chatUp
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Venom07%
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: chatup
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - chatUp
  keycloak:
    container_name: keycloak-chatUp
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - chatUp
    command:
      - "start-dev"

networks:
  chatUp:
    driver: bridge


volumes:
  postgres:
    driver:  local